from setuptools import setup
import io


setup(name='variantbrowser',
      description='Variant Browser: A tool for interpretation of variants from Genexus.',
      long_description=io.open('README.md', encoding='utf-8').read(),
      long_description_content_type='text/markdown',
      version='0.1.1',
      author='Sigve Landa',
      author_email='',
      license='MIT',
      url='',
      packages=['variantbrowser'],
      install_requires=['Flask>=3.0.1',
                        'Flask-Cors>=4.0.0',
                        'Flask-SQLAlchemy>=3.1.1',
                        'flask-jwt-extended>=4.6.0',
                        'SQLAlchemy>=2.0.25',
                        'MarkupSafe>=2.1.4',
                       ' Werkzeug>=3.0.1',
                        'numpy>=1.26.3',
                        'pandas>=2.2.0',
                        'openpyxl>=3.1.2',
                        'uuid>=1.30',
                        'maskpass>=0.3.7',
                        'waitress>=2.1.2'],

      entry_points={'console_scripts': ['vb = variantbrowser.__main__:main',
                                        'vb-backend = variantbrowser.run_backend_server:main',
                                        'vb-adduser = variantbrowser.cmd_functions:add_user',
                                        'vb-changepwd = variantbrowser.cmd_functions:change_pwd',
                                        'vb-generatedbs = variantbrowser.cmd_functions:generate_dbs',
                                        'vb-removesample = variantbrowser.cmd_functions:remove_sample',
                                        'vb-unlocksample = variantbrowser.cmd_functions:unapprove_sample']},
      test_suite=None)
